//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PresentationLayer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Books.
        /// </summary>
        internal static string ActiveBooks {
            get {
                return ResourceManager.GetString("ActiveBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pending to pay.
        /// </summary>
        internal static string ActiveFine {
            get {
                return ResourceManager.GetString("ActiveFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string AdminRole {
            get {
                return ResourceManager.GetString("AdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Settings.
        /// </summary>
        internal static string AdminSettings {
            get {
                return ResourceManager.GetString("AdminSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string AdminSetttingsSave {
            get {
                return ResourceManager.GetString("AdminSetttingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Click to Copy.
        /// </summary>
        internal static string AlertBoxTooltipCopyMsg {
            get {
                return ResourceManager.GetString("AlertBoxTooltipCopyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Books.
        /// </summary>
        internal static string AllBooks {
            get {
                return ResourceManager.GetString("AllBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Books.
        /// </summary>
        internal static string AvailableBooks {
            get {
                return ResourceManager.GetString("AvailableBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size has to be lower than.
        /// </summary>
        internal static string AvatarErrorMessage {
            get {
                return ResourceManager.GetString("AvatarErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned Book.
        /// </summary>
        internal static string BarName1 {
            get {
                return ResourceManager.GetString("BarName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed Book.
        /// </summary>
        internal static string BarName2 {
            get {
                return ResourceManager.GetString("BarName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        internal static string BookAuthor {
            get {
                return ResourceManager.GetString("BookAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf.
        /// </summary>
        internal static string BookBorrowShelf {
            get {
                return ResourceManager.GetString("BookBorrowShelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed Successfully.
        /// </summary>
        internal static string BookBorrowSuccessMsg {
            get {
                return ResourceManager.GetString("BookBorrowSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        internal static string BookCategory {
            get {
                return ResourceManager.GetString("BookCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover:.
        /// </summary>
        internal static string BookCover {
            get {
                return ResourceManager.GetString("BookCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Successfully.
        /// </summary>
        internal static string BookDialogAddSuccessMsg {
            get {
                return ResourceManager.GetString("BookDialogAddSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Book.
        /// </summary>
        internal static string BookDialogAddTitle {
            get {
                return ResourceManager.GetString("BookDialogAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        internal static string BookDialogUpdateSuccessMsg {
            get {
                return ResourceManager.GetString("BookDialogUpdateSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string BookDialogUpdateTitle {
            get {
                return ResourceManager.GetString("BookDialogUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN:.
        /// </summary>
        internal static string BookISBN {
            get {
                return ResourceManager.GetString("BookISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string BookLang {
            get {
                return ResourceManager.GetString("BookLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length:.
        /// </summary>
        internal static string BookLength {
            get {
                return ResourceManager.GetString("BookLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pg..
        /// </summary>
        internal static string BookListPageTagPostFix {
            get {
                return ResourceManager.GetString("BookListPageTagPostFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Year:.
        /// </summary>
        internal static string BookPublishYear {
            get {
                return ResourceManager.GetString("BookPublishYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        internal static string BookReturnFee {
            get {
                return ResourceManager.GetString("BookReturnFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned Successfully.
        /// </summary>
        internal static string BookReturnSuccessMsg {
            get {
                return ResourceManager.GetString("BookReturnSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Id.
        /// </summary>
        internal static string BookReturnTransactionMsg {
            get {
                return ResourceManager.GetString("BookReturnTransactionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no books in the library..
        /// </summary>
        internal static string BooksEmptyMessage {
            get {
                return ResourceManager.GetString("BooksEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf Number:.
        /// </summary>
        internal static string BookShelfNumber {
            get {
                return ResourceManager.GetString("BookShelfNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow Date.
        /// </summary>
        internal static string BookTableBorrowDate {
            get {
                return ResourceManager.GetString("BookTableBorrowDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Name.
        /// </summary>
        internal static string BookTableName {
            get {
                return ResourceManager.GetString("BookTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Date.
        /// </summary>
        internal static string BookTableReturnDate {
            get {
                return ResourceManager.GetString("BookTableReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string BookTitle {
            get {
                return ResourceManager.GetString("BookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Line:.
        /// </summary>
        internal static string BookTitleSec {
            get {
                return ResourceManager.GetString("BookTitleSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed Books.
        /// </summary>
        internal static string BorrowedBooks {
            get {
                return ResourceManager.GetString("BorrowedBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow.
        /// </summary>
        internal static string ButtonBorrow {
            get {
                return ResourceManager.GetString("ButtonBorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string ButtonReturn {
            get {
                return ResourceManager.GetString("ButtonReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 5 days Statistics.
        /// </summary>
        internal static string ChartTitle {
            get {
                return ResourceManager.GetString("ChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ChartXTitle {
            get {
                return ResourceManager.GetString("ChartXTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Count.
        /// </summary>
        internal static string ChartYTitle {
            get {
                return ResourceManager.GetString("ChartYTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Symbol.
        /// </summary>
        internal static string CurrencySymbol {
            get {
                return ResourceManager.GetString("CurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Info.
        /// </summary>
        internal static string DashboardChartInfoMenuTitle {
            get {
                return ResourceManager.GetString("DashboardChartInfoMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Scale Y Axis.
        /// </summary>
        internal static string DashboardChartScaleYAxis {
            get {
                return ResourceManager.GetString("DashboardChartScaleYAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no books available..
        /// </summary>
        internal static string DashboardPieChartEmptyMessage {
            get {
                return ResourceManager.GetString("DashboardPieChartEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed Book.
        /// </summary>
        internal static string DashboardStaffChartCurveTitle1 {
            get {
                return ResourceManager.GetString("DashboardStaffChartCurveTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Book.
        /// </summary>
        internal static string DashboardStaffChartCurveTitle2 {
            get {
                return ResourceManager.GetString("DashboardStaffChartCurveTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Book.
        /// </summary>
        internal static string DashboardStaffChartCurveTitle3 {
            get {
                return ResourceManager.GetString("DashboardStaffChartCurveTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Books By Days.
        /// </summary>
        internal static string DashboardStaffChartTitle {
            get {
                return ResourceManager.GetString("DashboardStaffChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string DashboardStaffChartXTitle {
            get {
                return ResourceManager.GetString("DashboardStaffChartXTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Count.
        /// </summary>
        internal static string DashboardStaffChartYTitle {
            get {
                return ResourceManager.GetString("DashboardStaffChartYTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days ago.
        /// </summary>
        internal static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days late.
        /// </summary>
        internal static string DaysLate {
            get {
                return ResourceManager.GetString("DaysLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days left.
        /// </summary>
        internal static string DaysLeft {
            get {
                return ResourceManager.GetString("DaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        internal static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Default.
        /// </summary>
        internal static string LoadDefault {
            get {
                return ResourceManager.GetString("LoadDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Mock Datas.
        /// </summary>
        internal static string LoadMockButton {
            get {
                return ResourceManager.GetString("LoadMockButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Empty.
        /// </summary>
        internal static string LoginEmailEmptyMessage {
            get {
                return ResourceManager.GetString("LoginEmailEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LoginEmailPlaceholderText {
            get {
                return ResourceManager.GetString("LoginEmailPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginExecuteButtonText {
            get {
                return ResourceManager.GetString("LoginExecuteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Empty.
        /// </summary>
        internal static string LoginPassEmptyMessage {
            get {
                return ResourceManager.GetString("LoginPassEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPassPlaceholderText {
            get {
                return ResourceManager.GetString("LoginPassPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string LoginUserTypeStaff {
            get {
                return ResourceManager.GetString("LoginUserTypeStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string LoginUserTypeStudent {
            get {
                return ResourceManager.GetString("LoginUserTypeStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbry..
        /// </summary>
        internal static string LogoText {
            get {
                return ResourceManager.GetString("LogoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Books.
        /// </summary>
        internal static string MyBooks {
            get {
                return ResourceManager.GetString("MyBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no borrowed books..
        /// </summary>
        internal static string MyBooksEmptyMessage {
            get {
                return ResourceManager.GetString("MyBooksEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewAdminPass {
            get {
                return ResourceManager.GetString("NewAdminPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no fine to pay.
        /// </summary>
        internal static string NoFine {
            get {
                return ResourceManager.GetString("NoFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Database.
        /// </summary>
        internal static string ResetDbButton {
            get {
                return ResourceManager.GetString("ResetDbButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Book.
        /// </summary>
        internal static string SearchBook {
            get {
                return ResourceManager.GetString("SearchBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to couldn&apos;t find.
        /// </summary>
        internal static string SearchNotFoundMessage {
            get {
                return ResourceManager.GetString("SearchNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Return Date:.
        /// </summary>
        internal static string SelectReturnDate {
            get {
                return ResourceManager.GetString("SelectReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Fine Amount.
        /// </summary>
        internal static string Setting1 {
            get {
                return ResourceManager.GetString("Setting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SettingsMockSuccessMessage {
            get {
                return ResourceManager.GetString("SettingsMockSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string StaffRole {
            get {
                return ResourceManager.GetString("StaffRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffs.
        /// </summary>
        internal static string Staffs {
            get {
                return ResourceManager.GetString("Staffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Staffs.
        /// </summary>
        internal static string StaffSettings {
            get {
                return ResourceManager.GetString("StaffSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar:.
        /// </summary>
        internal static string StudentAvatar {
            get {
                return ResourceManager.GetString("StudentAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string StudentEmail {
            get {
                return ResourceManager.GetString("StudentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string StudentName {
            get {
                return ResourceManager.GetString("StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string StudentPass {
            get {
                return ResourceManager.GetString("StudentPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string StudentRole {
            get {
                return ResourceManager.GetString("StudentRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        internal static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string StudentTableDelete {
            get {
                return ResourceManager.GetString("StudentTableDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string StudentTableDetails {
            get {
                return ResourceManager.GetString("StudentTableDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string StudentTableEdit {
            get {
                return ResourceManager.GetString("StudentTableEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Email.
        /// </summary>
        internal static string StudentTableEmail {
            get {
                return ResourceManager.GetString("StudentTableEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no registered students..
        /// </summary>
        internal static string StudentTableEmptyMessage {
            get {
                return ResourceManager.GetString("StudentTableEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        internal static string StudentTableName {
            get {
                return ResourceManager.GetString("StudentTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Number.
        /// </summary>
        internal static string StudentTableNumber {
            get {
                return ResourceManager.GetString("StudentTableNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        internal static string StudentTableOperations {
            get {
                return ResourceManager.GetString("StudentTableOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure.
        /// </summary>
        internal static string SureDialog {
            get {
                return ResourceManager.GetString("SureDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Parameters.
        /// </summary>
        internal static string SystemParameters {
            get {
                return ResourceManager.GetString("SystemParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total paid.
        /// </summary>
        internal static string TotalFine {
            get {
                return ResourceManager.GetString("TotalFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Staff.
        /// </summary>
        internal static string TotalStaff {
            get {
                return ResourceManager.GetString("TotalStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Student.
        /// </summary>
        internal static string TotalStudent {
            get {
                return ResourceManager.GetString("TotalStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book History.
        /// </summary>
        internal static string UserDetailsFormTitle {
            get {
                return ResourceManager.GetString("UserDetailsFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Staff.
        /// </summary>
        internal static string UserDialogAddStaffTitle {
            get {
                return ResourceManager.GetString("UserDialogAddStaffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Student.
        /// </summary>
        internal static string UserDialogAddStudentTitle {
            get {
                return ResourceManager.GetString("UserDialogAddStudentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Successfully.
        /// </summary>
        internal static string UserDialogAddSuccessMsg {
            get {
                return ResourceManager.GetString("UserDialogAddSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        internal static string UserDialogUpdateSuccessMsg {
            get {
                return ResourceManager.GetString("UserDialogUpdateSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string UserDialogUpdateTitle {
            get {
                return ResourceManager.GetString("UserDialogUpdateTitle", resourceCulture);
            }
        }
    }
}
