//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PresentationLayer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Books.
        /// </summary>
        internal static string ActiveBooks {
            get {
                return ResourceManager.GetString("ActiveBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string AdminRole {
            get {
                return ResourceManager.GetString("AdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Books.
        /// </summary>
        internal static string AllBooks {
            get {
                return ResourceManager.GetString("AllBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Books.
        /// </summary>
        internal static string AvailableBooks {
            get {
                return ResourceManager.GetString("AvailableBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned Book.
        /// </summary>
        internal static string BarName1 {
            get {
                return ResourceManager.GetString("BarName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed Book.
        /// </summary>
        internal static string BarName2 {
            get {
                return ResourceManager.GetString("BarName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        internal static string BookAuthor {
            get {
                return ResourceManager.GetString("BookAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        internal static string BookCategory {
            get {
                return ResourceManager.GetString("BookCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover:.
        /// </summary>
        internal static string BookCover {
            get {
                return ResourceManager.GetString("BookCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN:.
        /// </summary>
        internal static string BookISBN {
            get {
                return ResourceManager.GetString("BookISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string BookLang {
            get {
                return ResourceManager.GetString("BookLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length:.
        /// </summary>
        internal static string BookLength {
            get {
                return ResourceManager.GetString("BookLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Year:.
        /// </summary>
        internal static string BookPublishYear {
            get {
                return ResourceManager.GetString("BookPublishYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf Number:.
        /// </summary>
        internal static string BookShelfNumber {
            get {
                return ResourceManager.GetString("BookShelfNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string BookTitle {
            get {
                return ResourceManager.GetString("BookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed Books.
        /// </summary>
        internal static string BorrowedBooks {
            get {
                return ResourceManager.GetString("BorrowedBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow.
        /// </summary>
        internal static string ButtonBorrow {
            get {
                return ResourceManager.GetString("ButtonBorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string ButtonReturn {
            get {
                return ResourceManager.GetString("ButtonReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 5 days Statistics.
        /// </summary>
        internal static string ChartTitle {
            get {
                return ResourceManager.GetString("ChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ChartXTitle {
            get {
                return ResourceManager.GetString("ChartXTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Count.
        /// </summary>
        internal static string ChartYTitle {
            get {
                return ResourceManager.GetString("ChartYTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days late.
        /// </summary>
        internal static string DaysLate {
            get {
                return ResourceManager.GetString("DaysLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days left.
        /// </summary>
        internal static string DaysLeft {
            get {
                return ResourceManager.GetString("DaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadDefault.
        /// </summary>
        internal static string LoadDefault {
            get {
                return ResourceManager.GetString("LoadDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LoginEmailPlaceholderText {
            get {
                return ResourceManager.GetString("LoginEmailPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginExecuteButtonText {
            get {
                return ResourceManager.GetString("LoginExecuteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPassPlaceholderText {
            get {
                return ResourceManager.GetString("LoginPassPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string LoginUserTypeStaff {
            get {
                return ResourceManager.GetString("LoginUserTypeStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string LoginUserTypeStudent {
            get {
                return ResourceManager.GetString("LoginUserTypeStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbry..
        /// </summary>
        internal static string LogoText {
            get {
                return ResourceManager.GetString("LogoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Books.
        /// </summary>
        internal static string MyBooks {
            get {
                return ResourceManager.GetString("MyBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no fine to pay.
        /// </summary>
        internal static string NoFine {
            get {
                return ResourceManager.GetString("NoFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Book.
        /// </summary>
        internal static string SearchBook {
            get {
                return ResourceManager.GetString("SearchBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Return Date:.
        /// </summary>
        internal static string SelectReturnDate {
            get {
                return ResourceManager.GetString("SelectReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Fine Amount.
        /// </summary>
        internal static string Setting1 {
            get {
                return ResourceManager.GetString("Setting1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string StaffRole {
            get {
                return ResourceManager.GetString("StaffRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffs.
        /// </summary>
        internal static string Staffs {
            get {
                return ResourceManager.GetString("Staffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar:.
        /// </summary>
        internal static string StudentAvatar {
            get {
                return ResourceManager.GetString("StudentAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string StudentEmail {
            get {
                return ResourceManager.GetString("StudentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string StudentName {
            get {
                return ResourceManager.GetString("StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string StudentPass {
            get {
                return ResourceManager.GetString("StudentPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string StudentRole {
            get {
                return ResourceManager.GetString("StudentRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        internal static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
